import { Request, Response } from "express";
import jwt from 'jsonwebtoken';
import { DB_model } from "../model/Register_Schema";

interface GoogleUser  {
    id : string,
    name : string,
    email : string
};
 
export const Google_OAuth_Controller = async (req : Request, res : Response) => {
  
    if (!req.user) {
      return res.status(401).json({ response : "OAuth failed" });
    };

    const user = req.user as GoogleUser;    
    const DB_Users = await DB_model.findOne({Email : user.email});

    if (!DB_Users) {
        await DB_model.create({
            Username : user.name,
            Email : user.email,
            Provider : 'Google_Auth',
            ProviderId : user.id
        });
    };

    const paylaod : GoogleUser = { 
        id: user?.id, 
        name : user?.name,
        email: user?.email  
    };

    const token = jwt.sign(
      paylaod,
      process.env.JWT_SECRET as string
    );
    
    // console.log('Token Generated By OAuth-2.0 [ Google ] => ',token);
    
    res.cookie('cookies_Token', token);
    res.status(200).redirect('/secure/dashboard');
};

//Storing Data in Session and Retriving from Session 
// passport.serializeUser((user: Express.User, done) => {
//   done(null, user);     // What data will be stored in session
// });

// passport.deserializeUser((user: Express.User, done) => {
//   done(null, user);     // Extract user data from session
// });

// export const FaceBook_OAuth_Controller = (req : Request, res : Response) => {
 
//     if (!req.user) {
//       return res.status(401).json({ message: "OAuth failed" });
//     }

//     const user = req.user as User_Payload;    

//     const paylaod : User_Payload = { 
//         id: user?.id, 
//         name : user?.name,
//         email: user?.email  
//     };

//     const token = jwt.sign(
//       paylaod,
//       process.env.JWT_SECRET as string
//     );

//     res.cookie('cookies_Token', token);
//     res.redirect('http://localhost:3000/dashboard');
// };